### PR TITLE
Readd space workaround in pip::couchdb

### PR DESCRIPTION
**Pull request by ckaenzig**
It was really necessary, we weren't kidding.

### CODE REVIEW

**Comment by mcanevet** [comment]
:-( this is quite ugly... but if we need it then OK.

**Comment by ckaenzig** [comment]
@mcanevet Yes, it's ugly indeed, but we couldn't find any other solution. Having two packages with the same name but different providers is possible in Puppet 4.x, though ([PUP-1073](https://tickets.puppetlabs.com/browse/PUP-1073)).

**Comment by mcanevet** [comment]
@ckaenzig using `ensure_package()` function maybe?

**Comment by ckaenzig** [comment]
@mcanevet No, it's two different packages with the same name, not two references to the same package, i.e. we need both installed. One is couchdb itself (using the `yum` provider), the other is the python-couchdb bindings (using the `pip` provider). Both are called `couchdb`.

**Comment by mcanevet** [comment]
ok.

**Pull request merged**
